
== Agent API 

*POST a person*

----
 POST /person/
----

Person should be created with given fields.

====
Example:

post with below body

{
  "data": {
    "type": "person",
    "attributes": {
      "displayName": "First agent",
      "email": "a.b@c.d"
    }
   
  }
} 

and header Content-Type: application/vnd.api+json

will return following result:
....
{
    "data": {
        "id": "376f9c55-8c0b-4393-8f15-612fb66401ea",
        "type": "person",
        "links": {
            "self": "/api/v1/person/376f9c55-8c0b-4393-8f15-612fb66401ea"
        },
        "attributes": {
            "displayName": "First agent",
            "email": "a.b@c.d",
            "createdBy": "user",
            "createdOn": null
        }
    }
}
....
====

*PATCH a person*

----
PATCH /person/{id}
----

Person should be updated with given fields.

====
Example :

patch /person/376f9c55-8c0b-4393-8f15-612fb66401ea with below body
....
{
  "data": {
    "type": "person",
    "attributes": {
      "displayName": "First agent",
      "email": "a.b@c.e"
    }
   
  }
} 
....
and header Content-Type: application/vnd.api+json

will return below result:
....
{
    "data": {
        "id": "376f9c55-8c0b-4393-8f15-612fb66401ea",
        "type": "person",
        "links": {
            "self": "/api/v1/person/
             376f9c55-8c0b-4393-8f15-612fb66401ea"
        },
        "attributes": {
            "displayName": "First agent",
            "email": "a.b@c.e",
            "createdBy": "user",
            "createdOn": "2020-09-15T14:08:55.406823Z"
        }
    }
}
....
====

*Get One By id*
----
 GET /person/{id}
----

Would Return the person with that id if exists.

====
Example:

get /person/376f9c55-8c0b-4393-8f15-612fb66401ea and header of

Content-Type: application/vnd.api+json

will return below result:
....
{
    "data": {
        "id": "376f9c55-8c0b-4393-8f15-612fb66401ea",
        "type": "person",
        "links": {
            "self": "/api/v1/person/
             376f9c55-8c0b-4393-8f15-612fb66401ea"
        },
        "attributes": {
            "displayName": "First agent",
            "email": "a.b@c.d",
            "createdBy": "user",
            "createdOn": "2020-09-15T14:08:55.406823Z"
        }
    }
}
....
====

*Get all*

----
 GET /person/
----
Would return all persons in agent module.

Could add filer spec to filter the result as in

/person?filter[rsql]=( displayName=='attr1' or 
email=='attr2' )

Would return all persons in agent module meeting the query spec.

*DELETE a person*

----
DELETE /person/{id}
----

Person should be deleted.

====
Example:

delete /person/376f9c55-8c0b-4393-8f15-612fb66401ea
will delete the person.

Subsequent get /person/376f9c55-8c0b-4393-8f15-612fb66401ea
will return below
....
{
    "errors": [
        {
            "status": "404",
            "title": "PersonDto with ID 
             376f9c55-8c0b-4393-8f15-612fb66401ea Not Found.",
            "detail": "PersonDto with ID 
             376f9c55-8c0b-4393-8f15-612fb66401ea Not Found."
        }
    ]
} 
....
====