name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn verify
      - name: Run Checkstyle
        run: mvn checkstyle:check
      - name: Run SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:check
      - name: Run OWASP dependency-check (only on dev)
        run: mvn org.owasp:dependency-check-maven:check
        if: ${{ github.ref == 'refs/heads/dev' }}

      - name: Set IMAGE_TAG variable
        run: |
          echo "IMAGE_TAG=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Set up QEMU
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: ${{ github.ref == 'refs/heads/master' }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: aafcbicoe/agent-api:${{ env.IMAGE_TAG }}

